### ISSUE TITLE
你好，大佬我这一直提示不是最新版

### ISSUE THREAD

**Issue by lycheewisp** [tanyaofei/minecraft-fakeplayer#15]
Error occurred while enabling fakeplayer v0.1.9 (Is it up to date?)
这种情况如何解决用v0.1.8的时候也是这样

**Comment by tanyaofei** [comment]
这个不是提示插件不是最新版，而是 paper 在询问你 fakplayer 是否更新了。
你用的应该不是 1.20.1 的核心，我最近在支持 1.20.2，但是近期比较忙可能要一段时间

**Comment by wscds123** [comment]
Error occurred while enabling fakeplayer v0.1.9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at io.github.hello09x.fakeplayer.Main.onEnable(Main.java:48) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.1.79-universal.jar%23261!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.1.79-universal.jar%23261!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.1.79-universal.jar%23261!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:548) ~[forge-1.20.1-47.1.79-universal.jar%23261!/:997de31d-ddc9a2dad-d2eba2c8-47.2.1]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.1.79-universal.jar%23261!/:997de31d-ddc9a2dad-d2eba2c8-47.2.1]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23256!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23256!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23256!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23256!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23256!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Bukkit.getMinecraftVersion()'
        at io.github.hello09x.fakeplayer.util.nms.NMS$InstanceHolder.<clinit>(NMS.java:49) ~[?:?]
        at io.github.hello09x.fakeplayer.util.nms.NMS.getInstance(NMS.java:21) ~[?:?]
        at io.github.hello09x.fakeplayer.Main.onEnable(Main.java:38) ~[?:?]
        ... 11 more
[17:45:32 INFO]: [fakeplayer] Disabling fakeplayer v0.1.9

**Comment by wscds123** [comment]
1.20.1    mohist

**Comment by tanyaofei** [comment]
看日志的话似乎是核心没有很好的兼容 `paper` 的 API，缺少了一个 `Bukkit.getMinecraftVersion()` 的方法，这个方法是 `paper` 提供的
