### ISSUE TITLE
有考虑追加对1.20.4的兼容吗

### ISSUE THREAD

**Issue by SomeoneChen** [tanyaofei/minecraft-fakeplayer#22]
如题，我的服务器不知为何从spigot迁移后只能在1.20.4的paper端运行，其他版本都无法正常启动
您的插件似乎无法在1.20.4运行，您考虑兼容吗

**Comment by SomeoneChen** [comment]
另：在把插件存放在purpur运行时无法正确加载，错误日志如下
`[22:54:34 INFO]: [fakeplayer] Enabling fakeplayer v0.2.8
[22:54:34 ERROR]: Error occurred while enabling fakeplayer v0.2.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.hello09x.bedrock.i18n.I18n.asString(String)" because "io.github.hello09x.fakeplayer.core.command.CommandRegistry.i18n" is null
        at io.github.hello09x.fakeplayer.core.command.CommandRegistry.register(CommandRegistry.java:30) ~[fakeplayer-0.2.8.jar:?]
        at io.github.hello09x.fakeplayer.core.Main.onEnable(Main.java:44) ~[fakeplayer-0.2.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2125]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:54:34 INFO]: [fakeplayer] Disabling fakeplayer v0.2.8`

**Comment by tanyaofei** [comment]
暂时不会考虑支持 1.20.4，现在是在等 1.21

**Comment by tanyaofei** [comment]
https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.2.9
