### ISSUE TITLE
新加假人报错：PacketEvents 2.0 failed to inject

### ISSUE THREAD

**Issue by znc15** [tanyaofei/minecraft-fakeplayer#34]
核心：Purpur-1.20.1
相关记录：
```
[16:59:24 INFO]: Bot_YangXiaoMi_1 joined the game
[16:59:24 INFO]: Bot_YangXiaoMi_1[/127.0.0.1:25565] logged in with entity id 2187 at ([world]-54.5, 65.0, 28.5)
[16:59:24 INFO]: Bot_YangXiaoMi_1 lost connection: PacketEvents 2.0 failed to inject
[16:59:24 INFO]: [voicechat] Disconnecting client Bot_YangXiaoMi_1
[16:59:24 INFO]: Bot_YangXiaoMi_1 left the game
[16:59:24 WARN]: [PowerBoard] The player Bot_YangXiaoMi_1 has no Rank! Make sure that he has the correct permissions.
```

**Comment by Muska-Ami** [comment]
同样的问题，服务端信息：

```
[06:31:37 INFO]: Checking version, please wait...
[06:31:46 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2152 (MC: 1.20.4)
* You are running the latest version
```

创建假人时，会导致TrChat报错

```
[06:29:58 INFO]: Muska_Ami_Sama issued server command: /fp spawn
[06:29:58 ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.0
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyReflection$1.get(TinyReflection.java:153) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.getChannel(TinyProtocol.java:391) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:167) ~[TrChat-2.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.github.hello09x.fakeplayer.core.entity.FakePlayer.callLoginEvent(FakePlayer.java:235) ~[fakeplayer-0.2.9.jar:?]
        at io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:129) ~[fakeplayer-0.2.9.jar:?]
        at io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.2.9.jar:?]
        at io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.2.9.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:29:58 INFO]: [+]Muska_Ami_Sama_1
[06:29:58 INFO]: Muska_Ami_Sama_1[/127.0.0.2:25565] logged in with entity id 2617 at ([world]1318.5289432905943, 61.0, 1238.5220021027583)
[06:29:58 INFO]: Muska_Ami_Sama_1 lost connection: PacketEvents 2.0 failed to inject
[06:29:58 INFO]: [-]Muska_Ami_Sama_1
```

**Comment by znc15** [comment]
> 同样的问题，服务端信息：
> 
> ```
> [06:31:37 INFO]: Checking version, please wait...
> [06:31:46 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
> Previous: git-Purpur-2152 (MC: 1.20.4)
> * You are running the latest version
> ```
> 
> 创建假人时，会导致TrChat报错
> 
> ```
> [06:29:58 INFO]: Muska_Ami_Sama issued server command: /fp spawn
> [06:29:58 ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.0
> java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
>         at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
>         at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
>         at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
>         at me.arasple.mc.trchat.taboolib.module.nms.TinyReflection$1.get(TinyReflection.java:153) ~[TrChat-2.1.0.jar:?]
>         at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.getChannel(TinyProtocol.java:391) ~[TrChat-2.1.0.jar:?]
>         at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:167) ~[TrChat-2.1.0.jar:?]
>         at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
>         at io.github.hello09x.fakeplayer.core.entity.FakePlayer.callLoginEvent(FakePlayer.java:235) ~[fakeplayer-0.2.9.jar:?]
>         at io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:129) ~[fakeplayer-0.2.9.jar:?]
>         at io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.2.9.jar:?]
>         at io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.2.9.jar:?]
>         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [06:29:58 INFO]: [+]Muska_Ami_Sama_1
> [06:29:58 INFO]: Muska_Ami_Sama_1[/127.0.0.2:25565] logged in with entity id 2617 at ([world]1318.5289432905943, 61.0, 1238.5220021027583)
> [06:29:58 INFO]: Muska_Ami_Sama_1 lost connection: PacketEvents 2.0 failed to inject
> [06:29:58 INFO]: [-]Muska_Ami_Sama_1
> ```

而且回退版本也有，可能是哪个api的问题

**Comment by tanyaofei** [comment]
应该是跟这两个插件有兼容性问题，这两天我看看

**Comment by Esacpe-beep** [comment]
哪两个插件有兼容性问题

**Comment by znc15** [comment]
> 我玩的服务器和你版本一样 不知道什么问题

就是假人插件的问题

**Comment by tanyaofei** [comment]
应该是和 PacketEvent、TrChat 兼容有问题，TrChat 更新太频繁了？我记得我之前兼容过一次的了

**Comment by znc15** [comment]
> 应该是和 PacketEvent、TrChat 兼容有问题，TrChat 更新太频繁了？我记得我之前兼容过一次的了

TrChat没怎么更新好像

**Comment by tanyaofei** [comment]
1.20.x 用这个 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.2.10
1.21 用这个 https://github.com/tanyaofei/minecraft-fakeplayer/releases/tag/0.3.2
