### ISSUE TITLE
关于3.2版本在Paper核心运行时无法启动的问题

### ISSUE THREAD

**Issue by Ziyang-Bai** [tanyaofei/minecraft-fakeplayer#41]
我在Paper1.21核心运行了3.2版本在Enabling过程中遇到的问题
CommandAPI是存在的
```
[11:43:03 INFO]: [fakeplayer] Enabling fakeplayer v0.3.2
[11:43:03 ERROR]: Error occurred while enabling fakeplayer v0.3.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.hello09x.bedrock.i18n.I18n.asString(String)" because "io.github.hello09x.fakeplayer.core.command.CommandRegistry.i18n" is null
        at fakeplayer-0.3.2.jar/io.github.hello09x.fakeplayer.core.command.CommandRegistry.register(CommandRegistry.java:30) ~[fakeplayer-0.3.2.jar:?]
        at fakeplayer-0.3.2.jar/io.github.hello09x.fakeplayer.core.Main.onEnable(Main.java:44) ~[fakeplayer-0.3.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-38-1f5db50]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-38-1f5db50]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-38-1f5db50]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:43:03 INFO]: [fakeplayer] Disabling fakeplayer v0.3.2
```

**Comment by tanyaofei** [comment]
`0.3.5` 应该解决了这个问题
