### ISSUE TITLE
在1.21Purpur服务端中，假人无法正常的完成登录操作

### ISSUE THREAD

**Issue by Ziyang-Bai** [tanyaofei/minecraft-fakeplayer#52]
以下是伺服器控制台日志
值得注意的是服务器安装了LibreLogin插件
我确定配置文件的登录操作的正常的，在AuthME插件中假人可以正常的工作
在最后我来到了假人的位置，但是那里什么都没有
Tab键可以看见假人
但是tphere无法将假人召唤到位置
```
[19:37:23 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to LibreLogin v0.23.0
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.getUuid()" because "user" is null
        at LibreLogin.jar/xyz.kyngs.librelogin.paper.PaperListeners.onPreLogin(PaperListeners.java:130) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.callPreLoginEvent(FakePlayer.java:223) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$0(FakePlayer.java:118) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$joinAsync$1(CompletableTask.java:26) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$joinAsync$2(CompletableTask.java:38) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:37:25 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:37:25 ERROR]: [LibreLogin] AN IO OPERATION IS BEING PERFORMED ON THE MAIN THREAD! THIS IS A SERIOUS BUG!, PLEASE REPORT IT TO THE DEVELOPER OF THE PLUGIN AND ATTACH THE STACKTRACE BELOW!
[19:37:25 WARN]: java.lang.Throwable
[19:37:25 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.reportMainThread(AuthenticLibreLogin.java:837)
[19:37:25 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.database.provider.LibreLoginSQLDatabaseProvider.getByUUID(LibreLoginSQLDatabaseProvider.java:91)
[19:37:25 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:282)
[19:37:25 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:144)
[19:37:25 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[19:37:25 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:37:25 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:37:25 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:37:25 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:37:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[19:37:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[19:37:25 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:272)
[19:37:25 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48)
[19:37:25 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171)
[19:37:25 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19)
[19:37:25 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61)
[19:37:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[19:37:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[19:37:25 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752)
[19:37:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507)
[19:37:25 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636)
[19:37:25 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337)
[19:37:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[19:37:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:37:25 ERROR]: Could not pass event PlayerSpawnLocationEvent to LibreLogin v0.23.0
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.autoLoginEnabled()" because "user" is null
        at LibreLogin.jar/xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:289) ~[LibreLogin.jar:?]
        at LibreLogin.jar/xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:144) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:272) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:37:25 INFO]: Jing_jian_1 lost connection: Internal error, please try again later.
[19:37:25 INFO]: [voicechat] Disconnecting client Jing_jian_1
[19:37:25 INFO]: Jing_jian_1 left the game
[19:37:25 INFO]: Jing_jian_1 joined the game
[19:37:25 ERROR]: Illegal ChunkMap::addEntity for world world: ServerPlayer['Jing_jian_1'/28902, uuid='b962db3e-0098-39dc-9dcd-e7bd65729fe7', l='ServerLevel[world]', x=8.50, y=65.00, z=-507.50, cpos=[0, -32], tl=4630788, v=false, removed=UNLOADED_WITH_PLAYER](Jing_jian_1 at 8.5,65.0,-507.5)
java.lang.Throwable: null
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:892) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:393) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:37:25 WARN]: [ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup] Refusing to add removed entity: ServerPlayer['Jing_jian_1'/28902, uuid='b962db3e-0098-39dc-9dcd-e7bd65729fe7', l='ServerLevel[world]', x=8.50, y=65.00, z=-507.50, cpos=[0, -32], tl=4630788, v=false, removed=UNLOADED_WITH_PLAYER](Jing_jian_1 at 8.5,65.0,-507.5)
[19:37:25 INFO]: Jing_jian_1[/127.0.0.1:25565] logged in with entity id 28902 at ([world]8.5, 65.0, -507.5)
[19:37:47 INFO]: Jing_jian issued server command: /tphere Jing_jian
[19:37:50 INFO]: Jing_jian issued server command: /tphere Jing_jian
[19:37:51 INFO]: Jing_jian issued server command: /tphere Jing_jian
[19:37:54 INFO]: Jing_jian issued server command: /tphere Jing_jian_1
[19:38:02 INFO]: Jing_jian issued server command: /tphere Jing_jian_1
[19:38:06 INFO]: Jing_jian issued server command: /tphere
[19:38:18 INFO]: Jing_jian issued server command: /tphere Jing_jian_1
[19:38:34 INFO]: Jing_jian issued server command: /fp spawn
[19:38:34 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to LibreLogin v0.23.0
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.getUuid()" because "user" is null
        at LibreLogin.jar/xyz.kyngs.librelogin.paper.PaperListeners.onPreLogin(PaperListeners.java:130) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.callPreLoginEvent(FakePlayer.java:223) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$0(FakePlayer.java:118) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$joinAsync$1(CompletableTask.java:26) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$joinAsync$2(CompletableTask.java:38) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:38:43 ERROR]: [LibreLogin] AN IO OPERATION IS BEING PERFORMED ON THE MAIN THREAD! THIS IS A SERIOUS BUG!, PLEASE REPORT IT TO THE DEVELOPER OF THE PLUGIN AND ATTACH THE STACKTRACE BELOW!
[19:38:43 WARN]: java.lang.Throwable
[19:38:43 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.reportMainThread(AuthenticLibreLogin.java:837)
[19:38:43 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.database.provider.LibreLoginSQLDatabaseProvider.getByUUID(LibreLoginSQLDatabaseProvider.java:91)
[19:38:43 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:282)
[19:38:43 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:144)
[19:38:43 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[19:38:43 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:38:43 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:38:43 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:38:43 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:38:43 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[19:38:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[19:38:43 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:272)
[19:38:43 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48)
[19:38:43 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171)
[19:38:43 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19)
[19:38:43 WARN]:        at fakeplayer-0.3.3.jar//io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61)
[19:38:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[19:38:43 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[19:38:43 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752)
[19:38:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507)
[19:38:43 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636)
[19:38:43 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337)
[19:38:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[19:38:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:38:43 ERROR]: Could not pass event PlayerSpawnLocationEvent to LibreLogin v0.23.0
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.autoLoginEnabled()" because "user" is null
        at LibreLogin.jar/xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:289) ~[LibreLogin.jar:?]
        at LibreLogin.jar/xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:144) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:272) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:38:43 INFO]: Jing_jian_2 lost connection: Internal error, please try again later.
[19:38:43 INFO]: [voicechat] Disconnecting client Jing_jian_2
[19:38:43 INFO]: Jing_jian_2 left the game
[19:38:43 INFO]: Jing_jian_2 joined the game
[19:38:43 ERROR]: Illegal ChunkMap::addEntity for world world: ServerPlayer['Jing_jian_2'/30963, uuid='d5707d4d-3b73-3e19-a7be-473162bd0a67', l='ServerLevel[world]', x=148.50, y=63.00, z=-177.50, cpos=[9, -12], tl=0, v=false, removed=UNLOADED_WITH_PLAYER](Jing_jian_2 at 148.5,63.0,-177.5)
java.lang.Throwable: null
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:892) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:393) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.v1_21_R1.spi.NMSNetworkImpl.placeNewPlayer(NMSNetworkImpl.java:48) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.fakeplayer.core.entity.FakePlayer.lambda$spawnAsync$1(FakePlayer.java:171) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$0(CompletableTask.java:19) ~[fakeplayer-0.3.3.jar:?]
        at fakeplayer-0.3.3.jar/io.github.hello09x.bedrock.task.CompletableTask.lambda$join$4(CompletableTask.java:61) ~[fakeplayer-0.3.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1752) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:38:43 WARN]: [ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup] Refusing to add removed entity: ServerPlayer['Jing_jian_2'/30963, uuid='d5707d4d-3b73-3e19-a7be-473162bd0a67', l='ServerLevel[world]', x=148.50, y=63.00, z=-177.50, cpos=[9, -12], tl=0, v=false, removed=UNLOADED_WITH_PLAYER](Jing_jian_2 at 148.5,63.0,-177.5)
[19:38:43 INFO]: Jing_jian_2[/127.0.0.2:25565] logged in with entity id 30963 at ([world]148.5, 63.0, -177.5)
[19:42:02 INFO]: Jing_jian issued server command: /tp 278 77 -272
```

**Comment by tanyaofei** [comment]
这应该是与 `LibreLogin ` 兼容问题，我没有使用过这个插件，你可以简单介绍一下他的作用以及正常的玩家是如何通过他进行登陆的吗？

**Comment by tanyaofei** [comment]
可以将这个插件相关的配置发给我吗，我用默认配置测试是正常的。如果包含隐私内容可以邮件发送到 tan.yaofei@outlook.com

**Comment by tanyaofei** [comment]
这个问题的原因是因为 LibreLogin 会在 BungeeCord 登陆过程中创建用户相关数据，但是假人没有这个过程，因此他在服务器中登陆时会因为用户数据不存在而报错，并且 LibreLogin 会因为报错而踢掉玩家。

我在这个版本添加了 `prevent-kicked-on-spawning` 配置项，你可以把这个配置项设置为 `true` 来让假人强制性加入到游戏中，但是 `LibreLogin` 依然会在控制台中打印错误日志，但是应该不影响。


[fakeplayer-0.3.4.jar.zip](https://github.com/user-attachments/files/16369312/fakeplayer-0.3.4.jar.zip)

**Comment by Ziyang-Bai** [comment]
噢！现在这个插件已经正常的运作了，玩家可以正常的行动。很感谢！但是我认为ReadMe的config处需要更新一下。
