### ISSUE TITLE
Fatal error trying to convert fakeplayer v0.3.7:io/github/hello09x/fakeplayer/core/Main.class

### ISSUE THREAD

**Issue by hkkongou** [tanyaofei/minecraft-fakeplayer#65]
**Describe the bug / 描述你的 bug 情况**
无法使用

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
安装插件

**Server information / 服务器信息**
 - Software / 核心: purpur 1.20.1
 - Java: 21
 - Version / 版本 fakeplayer-0.3.7

**Additional context / 更多信息**
```
System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS) Host: Linux 6.5.0-45-generic (amd64)
Loading libraries, please wait...
[21:02:39 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:02:42 INFO]: Loaded 7 recipes
[21:02:43 INFO]: Starting minecraft server version 1.20.1
[21:02:43 INFO]: Loading properties
[21:02:43 INFO]: This server is running Purpur version git-Purpur-2060 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fbedef8 on HEAD)
[21:02:43 INFO]: Server Ping Player Sample Count: 12
[21:02:43 INFO]: Using 4 threads for Netty based IO
[21:02:43 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 8 worker threads, and gen parallelism of 8 threads
[21:02:43 WARN]: [Pufferfish] Will not enable SIMD! These optimizations are only safely supported on Java 17, Java 18, and Java 19.
[21:02:43 INFO]: Default game type: SURVIVAL
[21:02:43 INFO]: Generating keypair
[21:02:43 INFO]: Starting Minecraft server on *:25575
[21:02:43 INFO]: Using epoll channel type
[21:02:43 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[21:02:43 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/kelvin2/Desktop/main2/libraries/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/kelvin2/Desktop/main2/libraries/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/kelvin2/Desktop/main2/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/kelvin2/Desktop/main2/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[21:02:44 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/kelvin2/Desktop/main2/libraries/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loading 1 libraries... please wait
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loaded library /home/kelvin2/Desktop/main2/libraries/redis/clients/jedis/4.3.1/jedis-4.3.1.jar
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loaded library /home/kelvin2/Desktop/main2/libraries/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loaded library /home/kelvin2/Desktop/main2/libraries/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loaded library /home/kelvin2/Desktop/main2/libraries/org/json/json/20220320/json-20220320.jar
[21:02:45 INFO]: [SpigotLibraryLoader] [XConomy] Loaded library /home/kelvin2/Desktop/main2/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
[21:02:45 ERROR]: Fatal error trying to convert fakeplayer v0.3.7:io/github/hello09x/fakeplayer/core/Main.class
java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]
	at org.bukkit.craftbukkit.v1_20_R1.util.Commodore.convert(Commodore.java:171) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:403) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:522) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2060]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by tanyaofei** [comment]
需要 JAVA 21 以上

**Comment by tanyaofei** [comment]
估计 1.20.1 没办法兼容，尝试升级一下小版本号吧，我这 1.20.6 是正常的
