### ISSUE TITLE
假人無法成功召喚 版本為 fakeplayer-0.3.8-rc.4.jar

### ISSUE THREAD

**Issue by nate981120** [tanyaofei/minecraft-fakeplayer#74]
[20:26:34 INFO]: [MythicLib] [LightInjector] Late injection for player spawn2002
[20:26:34 WARN]: [HamsterAPI] Failed to inject player spawn2002 please contact 2LStudios for support about HamsterAPI as this can lead to vulnerabilities.
[20:26:34 INFO]: [CustomJoinAndQuitMessages] : [INFO] [+] spawn2002 加入了伺服器
[20:26:34 ERROR]: [InteractiveChat] [STDERR] {"clickEvent":{"action":"run_command","value":"/say <name>"},"hoverEvent":{"action":"show_text","value":[]},"extra":[{"color":"aqua","text":"["},{"color":"#83ff6f","text":"+"},{"color":"aqua","text":"] "},{"color":"#a157ff","text":"spawn2002 "},{"color":"dark_gray","text":"加入了伺服器"}],"text":""}
[20:26:34 WARN]: com.loohp.interactivechat.libs.com.google.gson.JsonParseException: Don't know how to turn [] into a Component
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:337)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:190)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:62)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1227)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1329)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1271)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:224)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:77)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1227)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1137)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:1047)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.com.google.gson.Gson.fromJson(Gson.java:982)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:89)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.libs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:41)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.utils.InteractiveChatComponentSerializer$InteractiveChatGsonComponentSerializer.deserialize(InteractiveChatComponentSerializer.java:378)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.utils.InteractiveChatComponentSerializer$InteractiveChatGsonComponentSerializer.deserialize(InteractiveChatComponentSerializer.java:348)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.utils.ChatComponentType.lambda$static$16(ChatComponentType.java:78)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.utils.ChatComponentType.convertFrom(ChatComponentType.java:115)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$14(OutMessagePacket.java:330)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:517)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$300(OutMessagePacket.java:87)
[20:26:34 WARN]:        at InteractiveChat-4.2.11.0 (1).jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:499)
[20:26:34 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[20:26:34 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[20:26:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:26:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:26:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:26:34 INFO]: spawn2002[/127.0.0.24:25565] logged in with entity id 1451120 at ([world_nether]0.0, -60.0, 0.0)
[20:26:34 INFO]: spawn2002 lost connection: PacketEvents 2.0 failed to inject
[20:26:34 INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] spawn2002 離開了伺服器

**Comment by tanyaofei** [comment]
看首页英文版readme，里面有解决方案，原因是paketevent 2.0 failed to inject
