### ISSUE TITLE
在声音更新抑制器范围内/fp kill的假人无法再次被召唤

### ISSUE THREAD

**Issue by PPGC777** [tanyaofei/minecraft-fakeplayer#75]
**Describe the bug / 描述你的 bug 情况**
在声音更新抑制器
[YouTube](https://www.youtube.com/watch?v=77M8Adnxmsw)
[B站搬运](https://www.bilibili.com/video/BV1Fx4y1s7jW/)
范围内使用/kill指令杀死的假人再次召唤时提示如图: 
![CH DK1GSGIS%5GB3Y @X0$C](https://github.com/user-attachments/assets/3be88fcc-e037-4d96-8b72-609509c55de4)
![3I097 QRAN9JR6UWT3W(XEF](https://github.com/user-attachments/assets/da2e8116-100d-4643-889b-305194949476)

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. 如图制作声音更新抑制器:
![6YK6TO{D6)J5~MY33A_ZJZ7](https://github.com/user-attachments/assets/f0aefd03-6cdd-4e88-b932-0ee0de4e791b)
两个假人分别站里在红框和蓝框位置并看向展示框(1号假人20tick周期使用use指令, 2号假人20tick周期使用attack指令, 目的是想用假人模拟放入物品到展示框和从展示框取出物品用来实现刷物品)
红色箭头位置为"外观是陷阱箱 本体是校频幽匿感测体"的声音更新抑制器, 讲台上的书是一本15页的书 翻到第11页(即输出信号强度11)
2. 发现的问题有两个:
①虽然两个假人的周期设置为20tick, 但是在更新抑制器范围内 两个假人均在1tick执行指令(已在非更新抑制器有效范围内执行上述指令 可以正常运行);
②在发现假人未按照指定的周期执行指令后, 使用/fp killall处死假人, 发现无法重新召唤假人(Tab界面能显示假人名字 /tphere指令无效, tp到假人为止发现是在被/fp kill的位置)

想知道有没有什么方法能救一下

**Server information / 服务器信息**
 - Software / 核心: [Purpur 1.20.2]
 - Java: [e.g. 21]
 - Version / 版本 [0.2.8]

**Comment by tanyaofei** [comment]
在这之前，你需要确认假人是否有权限，假人正常来说会按照20ticks的间隔来进行操作，除非说这一tick他的操作没有成功，那么可能是不会等待20ticks的

**Comment by PPGC777** [comment]
1 & 2: 经过测试, 在更新抑制器范围外的假人 使用相同指令可以做到1个假人向展示框放物品 另一个假人从展示框取出物品 并且周期为指令设置的周期; 在更新抑制器范围外的假人可以正常的spawn kill tphere等指令; (召唤假人的玩家拥有OP权限) (另外 在Fabric carpet端使用假人测试, 发现假人向展示框放入物品时会引起"IllegalArgumentException"异常而崩溃, 正常玩家向展示框放物品虽然也会引起"IllegalArgumentException"异常但不会导致游戏崩溃 从而达到复制物品的操作)
3: 经过测试 投影无法直接粘贴出更新抑制器的方块 所以我把存档和投影一同上传了(存档中的白色玻璃房和羊毛方块只是更新抑制器的大致范围, 准确范围是那个看起来像陷阱箱的校频幽匿感测体16格的球体范围; 存档中使用≥10的红石信号来让校频幽匿感测体只检测某种频率用于减少崩溃情况 但是请尽量减少发出声音的操作, 比如吃东西 扔雪球 放置方块 在非羊毛方块上非潜行走动 杀死怪物等等)
[KinhMC TEST.zip](https://github.com/user-attachments/files/16571673/KinhMC.TEST.zip)

**Comment by tanyaofei** [comment]
> 1 & 2: 经过测试, 在更新抑制器范围外的假人 使用相同指令可以做到1个假人向展示框放物品 另一个假人从展示框取出物品 并且周期为指令设置的周期; 在更新抑制器范围外的假人可以正常的spawn kill tphere等指令; (召唤假人的玩家拥有OP权限) (另外 在Fabric carpet端使用假人测试, 发现假人向展示框放入物品时会引起"IllegalArgumentException"异常而崩溃, 正常玩家向展示框放物品虽然也会引起"IllegalArgumentException"异常但不会导致游戏崩溃 从而达到复制物品的操作) 3: 经过测试 投影无法直接粘贴出更新抑制器的方块 所以我把存档和投影一同上传了(存档中的白色玻璃房和羊毛方块只是更新抑制器的大致范围, 准确范围是那个看起来像陷阱箱的校频幽匿感测体16格的球体范围; 存档中使用≥10的红石信号来让校频幽匿感测体只检测某种频率用于减少崩溃情况 但是请尽量减少发出声音的操作, 比如吃东西 扔雪球 放置方块 在非羊毛方块上非潜行走动 杀死怪物等等) [KinhMC TEST.zip](https://github.com/user-attachments/files/16571673/KinhMC.TEST.zip)

我没有使用过这个机器，所以我想了解一下。这个机器是不是类似于切门一样是通过报错来实现刷物品的，另外如果你有保留`IllegalArgumentException `的相关日志的话也可以一起发给我

**Comment by tanyaofei** [comment]
@PPGC777 对了，能否将坐标发给我，我导入地图之后不在机器周围

**Comment by tanyaofei** [comment]
经过测试，因为执行动作的时候发生了 `IllegalArgumentException` 异常，所以假人没有进行 interval 计算，这个可以进行修复。但是我在没有人别其他插件的个人服务器上是可以正常 kill 掉假人的

**Comment by tanyaofei** [comment]
[fakeplayer-0.3.9-b.1.jar.zip](https://github.com/user-attachments/files/16571893/fakeplayer-0.3.9-b.1.jar.zip)

试一下这个版本，我新增了以下代码

1. 无论行为是否执行成功，都执行 interval 运算
2. 任意一个行为抛出异常，不影响其他假人的行为执行

**Comment by PPGC777** [comment]
> > 1 & 2: 经过测试, 在更新抑制器范围外的假人 使用相同指令可以做到1个假人向展示框放物品 另一个假人从展示框取出物品 并且周期为指令设置的周期; 在更新抑制器范围外的假人可以正常的spawn kill tphere等指令; (召唤假人的玩家拥有OP权限) (另外 在Fabric carpet端使用假人测试, 发现假人向展示框放入物品时会引起"IllegalArgumentException"异常而崩溃, 正常玩家向展示框放物品虽然也会引起"IllegalArgumentException"异常但不会导致游戏崩溃 从而达到复制物品的操作) 3: 经过测试 投影无法直接粘贴出更新抑制器的方块 所以我把存档和投影一同上传了(存档中的白色玻璃房和羊毛方块只是更新抑制器的大致范围, 准确范围是那个看起来像陷阱箱的校频幽匿感测体16格的球体范围; 存档中使用≥10的红石信号来让校频幽匿感测体只检测某种频率用于减少崩溃情况 但是请尽量减少发出声音的操作, 比如吃东西 扔雪球 放置方块 在非羊毛方块上非潜行走动 杀死怪物等等) [KinhMC TEST.zip](https://github.com/user-attachments/files/16571673/KinhMC.TEST.zip)
> 
> 我没有使用过这个机器，所以我想了解一下。这个机器是不是类似于切门一样是通过报错来实现刷物品的，另外如果你有保留`IllegalArgumentException `的相关日志的话也可以一起发给我

简单来说是的, 切门可以通过更新跳略器(瞬时超过100万更新, 但是目标方块的周围6个方块可能还会更新, 在此之外不会再更新), 或者更新抑制器(通过某些异常'StackOverflowError' 'OutOfMemoryError' 'ClassCastException' 'IllegalArgumentException'既不让服务端崩溃 又可以阻止后续的方块更新)来实现

**Comment by PPGC777** [comment]
> [fakeplayer-0.3.9-b.1.jar.zip](https://github.com/user-attachments/files/16571893/fakeplayer-0.3.9-b.1.jar.zip)
> 
> 试一下这个版本，我新增了以下代码
> 
> 1. 无论行为是否执行成功，都执行 interval 运算
> 2. 任意一个行为抛出异常，不影响其他假人或者当前假人的其他行为继续执行

粗略测试了下, 在IAE更新抑制器范围内, 使用`/fp kill`指令杀死的假人可以顺利召唤, 但是通过`/kill`杀死的假人, 问题依旧:
 [05:23:40 INFO]: EVGA_233 issued server command: /fp spawn
 [05:23:40 INFO]: [fakeplayer] UUID of fake player EVGA_233_1 is 6061d210-0684-44aa-892a-3aaf7be895cd
 [05:23:40 INFO]: [GroupManager] Async Player Login event refresh data... 
 [05:23:40 INFO]: [GroupManager] Async Player Login event finshed. 
 [05:23:40 WARN]: [ViaVersion] Could not find UserConnection for logging-in player 6061d210-0684-44aa-892a-3aaf7be895cd
 [05:23:40 INFO]: EVGA_233_1 joined the game
 [05:23:40 INFO]: EVGA_233_1[/127.0.0.4:25565] logged in with entity id 710 at ([world_nether]4645.236911715352, 8.0, 4656.52653455432)
 [05:23:46 INFO]: EVGA_233 issued server command: /kill EVGA_233_1
 [05:23:54 INFO]: EVGA_233 issued server command: /fp spawn
 [05:23:54 INFO]: [fakeplayer] UUID of fake player EVGA_233_2 is a0ba0f29-6fda-4a7a-a391-c2a73ff0c46e
 [05:23:54 INFO]: [GroupManager] Async Player Login event refresh data... 
 [05:23:54 INFO]: [GroupManager] Async Player Login event finshed. 
 [05:23:54 WARN]: [ViaVersion] Could not find UserConnection for logging-in player a0ba0f29-6fda-4a7a-a391-c2a73ff0c46e
 [05:23:54 INFO]: EVGA_233_2 joined the game
 [05:23:54 INFO]: EVGA_233_2[/127.0.0.5:25565] logged in with entity id 770 at ([world]-535.5, 22.0, -421.5)
 [05:24:02 INFO]: EVGA_233 issued server command: /fp killall
 [05:24:02 INFO]: EVGA_233_2 lost connection: [fakeplayer] Command killall
 [05:24:02 INFO]: EVGA_233_2 left the game
 [05:24:02 INFO]: EVGA_233_1 lost connection: [fakeplayer] Command killall
 [05:24:02 INFO]: EVGA_233_1 left the game

假人在IAE更新抑制器范围内对准展示框右键的问题依旧, 比如执行`/fp use once bot_1`, 表现为一直在右键展示框, 后台记录信息如下:
 [05:22:26 WARN]: [fakeplayer] java.lang.IllegalArgumentException: Cannot get property BlockStateEnum{name=sculk_sensor_phase, clazz=class net.minecraft.world.level.block.state.properties.SculkSensorPhase, values=[inactive, active, cooldown]} as it does not exist in Block{minecraft:trapped_chest}
         at net.minecraft.world.level.block.state.IBlockDataHolder.c(IBlockDataHolder.java:95)
         at net.minecraft.world.level.block.SculkSensorBlock.h(SculkSensorBlock.java:209)
         at net.minecraft.world.level.block.SculkSensorBlock.n(SculkSensorBlock.java:213)
         at net.minecraft.world.level.block.entity.SculkSensorBlockEntity$a.a(SculkSensorBlockEntity.java:129)
         at net.minecraft.world.level.block.entity.CalibratedSculkSensorBlockEntity$a.a(CalibratedSculkSensorBlockEntity.java:43)
         at net.minecraft.world.level.gameevent.vibrations.VibrationSystem$b.a(VibrationSystem.java:292)
         at net.minecraft.world.level.gameevent.GameEventDispatcher.lambda$post$0(GameEventDispatcher.java:50)
         at net.minecraft.world.level.gameevent.EuclideanGameEventListenerRegistry.a(EuclideanGameEventListenerRegistry.java:74)
         at net.minecraft.world.level.gameevent.GameEventDispatcher.a(GameEventDispatcher.java:62)
         at net.minecraft.server.level.WorldServer.a(WorldServer.java:1907)
         at net.minecraft.world.level.GeneratorAccess.a(GeneratorAccess.java:107)
         at net.minecraft.world.entity.Entity.a(Entity.java:1655)
         at net.minecraft.world.entity.decoration.EntityItemFrame.a(EntityItemFrame.java:512)
         at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1174)
         at fakeplayer-0.3.9-b.1.jar//io.github.hello09x.fakeplayer.v1_20_R2.action.UseAction.tick(UseAction.java:64)
         at fakeplayer-0.3.9-b.1.jar//io.github.hello09x.fakeplayer.core.entity.action.BaseActionTicker.tick(BaseActionTicker.java:56)
         at fakeplayer-0.3.9-b.1.jar//io.github.hello09x.fakeplayer.core.manager.action.ActionManager.lambda$tick$1(ActionManager.java:76)
         at java.base/java.util.Collection.removeIf(Collection.java:576)
         at fakeplayer-0.3.9-b.1.jar//io.github.hello09x.fakeplayer.core.manager.action.ActionManager.tick(ActionManager.java:74)
         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
         at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1497)
         at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
         at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
         at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by tanyaofei** [comment]
@PPGC777 
1. 你这个更新抑制器本身就是通过异常来刷物品的，所以有报错日志是正常的，插件不会去处理这个异常
2. 你需要检查一下你是不是开启了死亡踢掉假人的配置, 也就是 `kick-on-dead`，如果是 `true` 则假人是不会自动退出游戏的，而是在原地等待复活，跟正常的玩家一样，这时候你需要使用 `/fp respawn` 去复活它，当然你可以设置为 `false` 让他退出游戏

**Comment by PPGC777** [comment]
> @PPGC777
> 
> 1. 你这个更新抑制器本身就是通过异常来刷物品的 _（让物品在世界掉落了，但是更新地形的时候发生异常从而出现双份物品）_ 所以有报错日志是正常的，插件不会去处理这个异常

现在的问题是假人在更新抑制器范围内并没有按设定的周期执行指令, 比如执行use once, 结果假人一直在执行use指令
另外, 可否再给假人增加一个`先use 再attack`的动作指令并按指定周期执行?

> 2. 你需要检查一下你是不是开启了死亡踢掉假人的配置, 也就是 `kick-on-dead`，如果是 `false` 则假人是不会自动退出游戏的，而是在原地等待复活，跟正常的玩家一样，这时候你需要使用 `/fp respawn` 去复活它，当然你可以设置为 `true` 让他退出游戏

已经确认`kick-on-dead`的值是`true`, `/fp respawn`提示`错误的命令参数`

**Comment by tanyaofei** [comment]
> 现在的我遇到的问题是假人在更新抑制器范围内并没有按设定的周期执行指令, 比如执行use once, 结果假人一直在执行use指令

这个原因是因为假人在执行 use 的时候发生了更新抑制的异常，导致动作没有被认定执行完毕，所以他会无限地重试。
我在你给的地图里已经可以正常通过两个假人，一个进行 use interval 20，一个进行 attack interval 20 实现刷物品了。

> 经确认kick-on-dead的值是true, /fp respawn提示错误的命令参数

这个我在我的服务器里也是复现了出来，问题应该在于世界移除假人实体的时候同样被抑制了，对于这种非正常游戏行为如果你能通过 /fp kill 来移除的话，我觉得插件不需要再处理这个问题了

**Comment by tanyaofei** [comment]
[fakeplayer-0.3.9-b.2.jar.zip](https://github.com/user-attachments/files/16573793/fakeplayer-0.3.9-b.2.jar.zip)

这个版本我在假人创建的时候强制恢复生命值为 20，可以解决你 kill 掉后再次召唤失败的问题

**Comment by PPGC777** [comment]
> [fakeplayer-0.3.9-b.2.jar.zip](https://github.com/user-attachments/files/16573793/fakeplayer-0.3.9-b.2.jar.zip)
> 
> 这个版本我在假人创建的时候强制恢复生命值为 20，可以解决你 kill 掉后再次召唤失败的问题

感谢大佬解决再次召唤问题;
虽然我这里的假人use和attack还是无法做到指定周期(依旧表现为动作被抑制 然后不断重试), 不过无所谓了, 已经使用按键精灵实现AFK.
再次感谢~~~

**Comment by tanyaofei** [comment]
> > [fakeplayer-0.3.9-b.2.jar.zip](https://github.com/user-attachments/files/16573793/fakeplayer-0.3.9-b.2.jar.zip)
> > 这个版本我在假人创建的时候强制恢复生命值为 20，可以解决你 kill 掉后再次召唤失败的问题
> 
> 感谢大佬解决再次召唤问题; 虽然我这里的假人use和attack还是无法做到指定周期(依旧表现为动作被抑制 然后不断重试), 不过无所谓了, 已经使用按键精灵实现AFK. 再次感谢~~~

这个不应该呀，现在 interval 计算即使发生异常也会处理的，只有 once 是不生效的, interval 会生效的

**Comment by PPGC777** [comment]
> > > [fakeplayer-0.3.9-b.2.jar.zip](https://github.com/user-attachments/files/16573793/fakeplayer-0.3.9-b.2.jar.zip)
> > > 这个版本我在假人创建的时候强制恢复生命值为 20，可以解决你 kill 掉后再次召唤失败的问题
> > 
> > 
> > 感谢大佬解决再次召唤问题; 虽然我这里的假人use和attack还是无法做到指定周期(依旧表现为动作被抑制 然后不断重试), 不过无所谓了, 已经使用按键精灵实现AFK. 再次感谢~~~
> 
> 这个不应该呀，现在 interval 计算即使发生异常也会处理的，只有 once 是不生效的, interval 会生效的

啊这....我的问题 指令弄错了, 一直用的continuous来测试的

**Comment by tanyaofei** [comment]
hhh问题解决就好

**Comment by PPGC777** [comment]
> hhh问题解决就好

甚至可以用interval 1来快速刷物品, 四舍五入就是个36000盒/h的全物品复制机, 如果是64堆叠的物品来算, 每小时效率可以有62208k物品, 财富自由了属于是
