### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by ning-g-mo** [tanyaofei/minecraft-fakeplayer#80]
**Describe the bug / 描述你的 bug 情况**
A clear and concise description of what the bug is. / 简单描述这是一个什么 bug

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. ...
2. ...
3. ...
4. ...

**Server information / 服务器信息**
 - Software / 核心: [e.g. leaves 1.21.1]
 - Java: [e.g. 21]
 - Version / 版本 [e.g. 0.3.8]

**Additional context / 更多信息**
Add any other context about the problem here. Such as log and plugin list / 添加更多有帮助的信息，如插件列表、日志
[17:52:46 ERROR]: Error occurred while enabling fakeplayer v0.3.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.google.inject.Injector.injectMembers(Object)" because "this.injector" is null
        at 假人fakeplayer-0.jar/io.github.hello09x.fakeplayer.core.Main.onEnable(Main.java:60) ~[假人fakeplayer-0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:511) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:333) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.1.jar:1.21.1-47-8be1ec2]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by tanyaofei** [comment]
更新到最新版本
