### ISSUE TITLE
未知错误不支持的API版本1.20

### ISSUE THREAD

**Issue by 1397108563** [tanyaofei/minecraft-fakeplayer#83]
[14:11:55] [Server thread/ERROR]: Could not load 'plugins/fakeplayer-0.3.9.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
	at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:11:55] [Server thread/INFO]: [CommandAPI] Loading CommandAPI v9.1.0

**To Reproduce / 如何触发**
Steps to reproduce the behavior: / 触发的步骤
1. 1.18.2purpur服务器
2. 添加fakeplayer0.3.9
3. 添加CommandAPI9.5.3
4. CommandAPI正常运行，但fakeplayer出现上述崩溃

**Server information / 服务器信息**
 - Software / 核心: Purpur 1.18.2
 - Java: openjdk 21
 - Version / 版本 0.3.9

**Additional context / 更多信息**
额外添加插件：ALLmusic3.1.7 Authme5.6.0

**Comment by 1397108563** [comment]
对不起，我没有注意到插件的版本要求。
